name:
  Cron Job
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "0 0 * * *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: convert to ONNX
      run: |
        python convert_torch_to_onnx.py pytorch_model_weights.pth
    - name: Run test case 1
      run: |
        python test_onnx.py n01440764_tench.jpeg
    - name: Run test case 2
      run: |
        python test_onnx.py n01632777_axolotl.jpeg
